version: "3.5"

# you can disable any of services by using comment

services:
  pdfMaker:
    build:
      context: .
      dockerfile: submodules/latex/Dockerfile
    container_name: pdfMaker
    image: marmot0814/latex
    command: ["sleep","infinity"]
    restart: on-failure
    volumes:
      - ".:/storage"
